name: My Workflow
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: regexp.MustCompile(`(?m)(\[(.+)\]\(([^\s]+)(?:\s"(.+)")?\))(?!\s-\s\<a\sclass=\"archival\")`)
          replace: '$1 - <a class="archival" aria-label="Internet Archive copy of previous link" href="http://web.archive.org/web/$3">(archive)</a>'
          include: "test1.md"        
        
